1модуль
Ekaterina-Kirpi/java-explore-with-me pull request #8
Opened 2023-08-29 13:48 UTC by Ekaterina-Kirpi

2023-08-30 10:08 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть пара замечаний, которые необходимо исправить!

Желаю удачи!

2023-08-30 10:08 UTC, LexLippi commented on stats/stats-client/src/main/java/ru/practicum/ewm/stats/client/StatsClient.java
> +        ResponseEntity<Object> response;
Зачем это? 
Можно же всю дальнейшую обработку выполнить в блоке `try` и не потребуется объявлять неинициализированную переменную

2023-08-30 10:08 UTC, LexLippi commented on stats/stats-client/src/main/java/ru/practicum/ewm/stats/client/StatsClient.java
> +    public ResponseEntity<Object> getStats(LocalDateTime start, LocalDateTime end, List<String> uris, Boolean unique) {
Вопрос, аналогичный методу выше

2023-08-30 10:08 UTC, LexLippi commented on stats/stats-dto/src/main/java/ru/practicum/ewm/stats/dto/EndpointHitDto.java
> +    private LocalDateTime timestamp;
`timestamp` это скорее про тип данных, а это же время, которое что-то обозначает. Например, `hitTimestamp`

2023-08-30 10:08 UTC, LexLippi commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/server/StatsController.java
> +    public List<ViewStats> getStats(@RequestParam @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime start,
Это лучше вынести в константу проекта, скорее всего в будущем не только здесь бужешь это использовать

2023-08-30 10:08 UTC, LexLippi commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/server/StatsService.java
> +        } else {
`else` не нужен

2023-08-30 10:08 UTC, LexLippi commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/server/StatsService.java
> +            return statsRepository.findHitsWithUniqueIpWithoutUris(start, end);
Можно тернарный оператор использовать

2023-08-30 10:08 UTC, LexLippi commented on stats/stats-server/src/main/resources/schema.sql
> +    timestamp  TIMESTAMP
1. лучше не называть колонку так же, как и тип данных
2. явно не хватает `not null` ограничений
3. по-хорошему не хватает индексов (это необязательно, но обычно на все поля по которым осуществляется поиск навешиваются индексы)

https://www.postgresql.org/docs/current/indexes.html

2023-08-30 10:08 UTC, LexLippi commented on stats/stats-server/src/main/resources/schema.sql
> +    uri        VARCHAR(255),
Длина `uri` может быть куда больше:

https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

2023-08-31 01:15 UTC, Ekaterina-Kirpi commented on docker-compose.yml
> +#    image: postgres:14-alpine
+

2023-08-31 01:15 UTC, Ekaterina-Kirpi commented on main/pom.xml
> +    <artifactId>main</artifactId>
+

2023-08-31 01:15 UTC, Ekaterina-Kirpi commented on stats/stats-client/src/main/java/ru/practicum/ewm/stats/client/StatsClient.java
> +        ResponseEntity<Object> response;
+

2023-08-31 01:15 UTC, Ekaterina-Kirpi commented on stats/stats-dto/src/main/java/ru/practicum/ewm/stats/dto/EndpointHitDto.java
> +    private LocalDateTime timestamp;
+

2023-08-31 01:15 UTC, Ekaterina-Kirpi commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/server/StatsController.java
> +    public List<ViewStats> getStats(@RequestParam @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime start,
+

2023-08-31 01:15 UTC, Ekaterina-Kirpi commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/server/StatsService.java
> +        } else {
+

2023-08-31 01:15 UTC, Ekaterina-Kirpi commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/server/StatsService.java
> +            return statsRepository.findHitsWithUniqueIpWithoutUris(start, end);
+

2023-08-31 01:15 UTC, Ekaterina-Kirpi commented on stats/stats-server/src/main/resources/schema.sql
> +    uri        VARCHAR(255),
+

2023-08-31 01:15 UTC, Ekaterina-Kirpi commented on stats/stats-server/src/main/resources/schema.sql
> +    timestamp  TIMESTAMP
+

2023-08-31 01:28 UTC, Ekaterina-Kirpi commented on stats/stats-client/src/main/java/ru/practicum/ewm/stats/client/StatsClient.java
> +public class StatsClient {
+

2023-08-31 01:51 UTC, Ekaterina-Kirpi commented on stats/stats-client/src/main/java/ru/practicum/ewm/stats/client/StatsClient.java
> +public class StatsClient {
+

2023-08-31 10:34 UTC, Ekaterina-Kirpi commented on stats/stats-server/src/main/resources/schema.sql
> +    timestamp  TIMESTAMP
с твоего разрешения оставлю так, тк переименовав, падают тесты, в запросах идет timestamp

2023-09-01 07:13 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи на следующих этапах диплома!

2023-09-01 12:11 UTC, merged