Модуль2
Ekaterina-Kirpi/java-explore-with-me pull request #9
Opened 2023-09-05 02:33 UTC by Ekaterina-Kirpi

2023-09-05 08:50 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которые надо исправить!

Желаю удачи!

2023-09-05 08:50 UTC, LexLippi commented on main-service/src/main/java/ru/practicum/ewm/categories/Category.java
> +@ToString
Проще использовать аннотацию `Data`, которая объединяет эти понятия

https://projectlombok.org/features/Data

2023-09-05 08:50 UTC, LexLippi commented on main-service/src/main/java/ru/practicum/ewm/categories/CategoryService.java
> +        categoryRepository.deleteById(categoryId);
Обычно метод `deleteById` возвращает количество строк на который повлияло это действие, и если оно равно нулю, значит строка не была найдена, и можно выбросить ошибку.

Можно постараться убрать лишний запрос

2023-09-05 08:50 UTC, LexLippi commented on main-service/src/main/java/ru/practicum/ewm/categories/controller/CategoryControllerPublic.java
> +                                           @RequestParam(value = "size", defaultValue = "10") @Positive Integer size) {
если значение в `value` и название переменной совпадают, то `value` можно не указывать

2023-09-05 08:50 UTC, LexLippi commented on main-service/src/main/java/ru/practicum/ewm/compilations/Compilation.java
> +@ToString
`Data`

2023-09-05 08:50 UTC, LexLippi commented on main-service/src/main/resources/schema.sql
> +DROP TABLE IF EXISTS requests CASCADE;
По возможности убрать это.
Представь себе, кто будет пользоваться продакшен-приложением, если мы при каждом релизе будем удалять все данные пользователей?

2023-09-05 08:50 UTC, LexLippi commented on main-service/src/main/resources/schema.sql
> +    lon FLOAT
Могут быть `null`?

2023-09-05 08:50 UTC, LexLippi commented on main-service/src/main/resources/schema.sql
> +    status       VARCHAR(50)
могут быть `null`?

2023-09-05 08:50 UTC, LexLippi commented on main-service/src/main/resources/schema.sql
> +    event_id       BIGINT REFERENCES events(id),
могут быть `null`?

2023-09-05 08:50 UTC, LexLippi commented on main-service/src/main/java/ru/practicum/ewm/users/UserController.java
> +                                  @RequestParam(value = "size", defaultValue = "10") @Positive Integer size) {
Про это писал уже

2023-09-05 08:50 UTC, LexLippi commented on main-service/src/main/java/ru/practicum/ewm/users/User.java
> +@ToString
`Data`

2023-09-05 08:50 UTC, LexLippi commented on main-service/src/main/java/ru/practicum/ewm/requests/model/ParticipationRequest.java
> +@ToString
`Data`

2023-09-05 08:50 UTC, LexLippi commented on main-service/src/main/java/ru/practicum/ewm/requests/dto/ConfirmedRequests.java
> +@Setter
`Data`

2023-09-05 08:50 UTC, LexLippi commented on main-service/src/main/java/ru/practicum/ewm/locations/Location.java
> +@ToString
`Data`

2023-09-05 08:50 UTC, LexLippi commented on main-service/src/main/java/ru/practicum/ewm/events/model/Event.java
> +@ToString
`Data`

2023-09-05 08:50 UTC, LexLippi commented on main-service/src/main/java/ru/practicum/ewm/events/controller/EventControllerPrivate.java
> +                                         @RequestParam(value = "size", defaultValue = "10") @Positive Integer size) {
писал об этом

2023-09-05 10:12 UTC, Ekaterina-Kirpi commented on main-service/src/main/java/ru/practicum/ewm/categories/Category.java
> +@ToString
+

2023-09-05 10:12 UTC, Ekaterina-Kirpi commented on main-service/src/main/java/ru/practicum/ewm/categories/CategoryService.java
> +        categoryRepository.deleteById(categoryId);
+

2023-09-05 10:13 UTC, Ekaterina-Kirpi commented on main-service/src/main/java/ru/practicum/ewm/categories/controller/CategoryControllerPublic.java
> +                                           @RequestParam(value = "size", defaultValue = "10") @Positive Integer size) {
+

2023-09-05 10:13 UTC, Ekaterina-Kirpi commented on main-service/src/main/resources/schema.sql
> +    lon FLOAT
+

2023-09-05 10:13 UTC, Ekaterina-Kirpi commented on main-service/src/main/resources/schema.sql
> +    status       VARCHAR(50)
+

2023-09-05 10:13 UTC, Ekaterina-Kirpi commented on main-service/src/main/resources/schema.sql
> +    event_id       BIGINT REFERENCES events(id),
+

2023-09-05 10:14 UTC, Ekaterina-Kirpi commented on main-service/src/main/java/ru/practicum/ewm/users/User.java
> +@ToString
+

2023-09-05 10:14 UTC, Ekaterina-Kirpi commented on main-service/src/main/java/ru/practicum/ewm/requests/model/ParticipationRequest.java
> +@ToString
+

2023-09-05 10:14 UTC, Ekaterina-Kirpi commented on main-service/src/main/java/ru/practicum/ewm/requests/dto/ConfirmedRequests.java
> +@Setter
+

2023-09-05 10:14 UTC, Ekaterina-Kirpi commented on main-service/src/main/java/ru/practicum/ewm/locations/Location.java
> +@ToString
+

2023-09-05 10:14 UTC, Ekaterina-Kirpi commented on main-service/src/main/java/ru/practicum/ewm/events/model/Event.java
> +@ToString
+

2023-09-05 10:14 UTC, Ekaterina-Kirpi commented on main-service/src/main/java/ru/practicum/ewm/events/controller/EventControllerPrivate.java
> +                                         @RequestParam(value = "size", defaultValue = "10") @Positive Integer size) {
+

2023-09-06 06:57 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи на заключительном этапе диплома!

2023-09-06 07:01 UTC, merged